name: Docker Hub release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  docker-hub:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Login
      run: docker login -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" -p "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" "docker.io" 
    - name: Build 
      run: docker build -t cyclenerd/scp-tools-gitlab:release-${{ github.ref#refs/tags/v }} .
    - name: Push
      run: docker push cyclenerd/scp-tools-gitlab:release-${{ github.ref#refs/tags/v }}
